const SET_AUTH_REDUCER = 'SET_AUTH_REDUCER';

const SET_MASTER_MENU_REDUCER = 'SET_MASTER_MENU_REDUCER';
const SET_MASTER_PRODUCT_CATEGORY_REDUCER = 'SET_MASTER_PRODUCT_CATEGORY_REDUCER';
const SET_MASTER_PRODUCT_GROUP_REDUCER = 'SET_MASTER_PRODUCT_GROUP_REDUCER';
const SET_MASTER_PRODUCTS_REDUCER = 'SET_MASTER_PRODUCTS_REDUCER';
const SET_MASTER_BILLER_REDUCER = 'SET_MASTER_BILLER_REDUCER';
const SET_MASTER_USERS_REDUCER = 'SET_MASTER_USERS_REDUCER';
const SET_MASTER_PAYMENT_METHODS_REDUCER = 'SET_MASTER_PAYMENT_METHODS_REDUCER';
const SET_MASTER_SETTING_FEE_UPLINE_REDUCER = 'SET_MASTER_SETTING_FEE_UPLINE_REDUCER';
const SET_MASTER_BANKS_REDUCER = 'SET_MASTER_BANKS_REDUCER';

const SET_TRANSACTION_ADJUST_SALDO_REDUCER = 'SET_TRANSACTION_ADJUST_SALDO_REDUCER';

const SET_POINT_EXCHANGE_PRODUCTS_REDUCER = 'SET_POINT_EXCHANGE_PRODUCTS_REDUCER';

export {
  SET_AUTH_REDUCER,
  SET_MASTER_MENU_REDUCER,
  SET_MASTER_PRODUCT_CATEGORY_REDUCER,
  SET_MASTER_PRODUCT_GROUP_REDUCER,
  SET_MASTER_PRODUCTS_REDUCER,
  SET_MASTER_BILLER_REDUCER,
  SET_MASTER_USERS_REDUCER,
  SET_MASTER_PAYMENT_METHODS_REDUCER,
  SET_TRANSACTION_ADJUST_SALDO_REDUCER,
  SET_MASTER_SETTING_FEE_UPLINE_REDUCER,
  SET_POINT_EXCHANGE_PRODUCTS_REDUCER,
  SET_MASTER_BANKS_REDUCER,
};
