const SET_AUTH_REDUCER = 'SET_AUTH_REDUCER';
const SET_MASTER_MENU_REDUCER = 'SET_MASTER_MENU_REDUCER';
const SET_MASTER_PRODUCT_CATEGORY_REDUCER = 'SET_MASTER_PRODUCT_CATEGORY_REDUCER';
const SET_MASTER_PRODUCT_GROUP_REDUCER = 'SET_MASTER_PRODUCT_GROUP_REDUCER';


export { SET_AUTH_REDUCER, SET_MASTER_MENU_REDUCER, SET_MASTER_PRODUCT_CATEGORY_REDUCER, SET_MASTER_PRODUCT_GROUP_REDUCER };

